version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - default
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    links:
      - db:db
